[versions]
agp = "8.13.0" # see https://developer.android.com/studio/releases/gradle-plugin
androidxComposeMaterial3 = "1.5.0-alpha04" # see https://developer.android.com/jetpack/androidx/releases/compose-material3
androidxComposeMaterialIconsExtended = "1.7.8"
androidxCore = "1.17.0"
androidxEspressoCore = "3.7.0"
androidxHilt = "1.3.0"
androidxLifecycle = "2.9.4"
androidxSplashScreen = "1.1.0-rc01"
androidxTestJunit = "1.3.0"
arturboschDetekt = "1.23.8"
assertk = "0.28.1"
hilt = "2.57.1"
junit = "4.13.2"
kotlin = "2.2.20" # see https://developer.android.com/jetpack/androidx/releases/compose-kotlin
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.20-2.0.3" # https://search.maven.org/artifact/com.google.devtools.ksp/symbol-processing-api
okio = "3.16.0"
undercouchDownload = "5.6.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
arturbosch-detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturboschDetekt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
undercouch-download-plugin = { id = "de.undercouch.download", version.ref = "undercouchDownload" }

[libraries]
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxComposeMaterialIconsExtended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version.ref = "assertk" }
google-dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "hilt" }
google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
okio-assetfilesystem = { group = "com.squareup.okio", name = "okio-assetfilesystem", version.ref = "okio" }
